Add setManualPrice mutation
vtex-apps/order-items pull request #31
Opened 2020-09-10 20:14 UTC by jeffersontuc

#### What problem is this solving?

The same as [checkout-graphql#89](https://github.com/vtex/checkout-graphql/pull/89)

#### How to test it?

N/A
#### Screenshots or example usage:

#### Describe alternatives you've considered, if any.

#### Related to / Depends on

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](put .gif link here - can be found under "advanced" on giphy)

2020-09-10 20:36 UTC, lucasecdb commented on react/OrderItems.tsx
> +  const setManualPriceTask = (price: number, itemIndex: number) => {
can you wrap this function inside a `useCallback`?

2020-09-10 20:36 UTC, lucasecdb commented on react/OrderItems.tsx
> +  const setManualPrice = (price: number, itemIndex: number) => {
same as above

2020-09-22 14:46 UTC, lucasecdb reviewed
LGTM! can you fix the lint issues? I think if you run `yarn lint --fix` in the root folder should be good

2020-09-24 14:44 UTC, lucasecdb approved these changes

2020-09-24 18:51 UTC, wdsrocha commented on CHANGELOG.md
> +
nit to keep consistency
```suggestion
```

2020-09-24 18:53 UTC, wdsrocha approved these changes

2020-09-25 12:45 UTC, lucasecdb requested changes
Tests are failing, can you take a look?

2020-09-25 12:46 UTC, jeffersontuc commented
> Tests are failing, can you take a look?

Yeah, I'm looking at it! Thanks!

2020-09-25 12:53 UTC, jeffersontuc commented
> Tests are failing, can you take a look?

Apparently, it can't find the `SetManualPrice` mutation. I'll wait some minutes after trying to re-run again, since I just  deployed the version of the `checkout-resources` which adds this mutation.

2020-09-25 12:55 UTC, lucasecdb commented
> Apparently, it can't find the `SetManualPrice` mutation. I'll wait some minutes after trying to re-run again, since I just deployed the version of the `checkout-resources` which adds this mutation.

I think you need to mock it, no? since the package toolbelt injects here is only for the typings

2020-09-25 13:02 UTC, jeffersontuc commented
> > Apparently, it can't find the `SetManualPrice` mutation. I'll wait some minutes after trying to re-run again, since I just deployed the version of the `checkout-resources` which adds this mutation.
> 
> I think you need to mock it, no? since the package toolbelt injects here is only for the typings

I do, indeed! Thanks

2020-09-25 13:14 UTC, lucasecdb approved these changes

2020-09-25 13:19 UTC, merged